// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxpgfhgmqpocxjqeuurr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4cGdmaGdtcXBvY3hqcWV1dXJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjQ2NzIsImV4cCI6MjA3MjQwMDY3Mn0.jMGTFp1m8XsI3Yiz63GtVf2SKuwVE9G1mRs5l5b7SXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});